server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service # order服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: Guangzhou
        #namespace: 53a32d4a-c27a-4d0e-88ac-dcde8234e7ec # dev环境 配置命名空间namespace
        ephemeral: false  # 是否为临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# eureka 客户端配置
# eureka地址信息
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.1.0.1:10086/eureka

# 设置对user-service的负载均衡策略
# com.netflix.loadbalancer.RandomRule 随机
# com.alibaba.cloud.nacos.ribbon.NacosRule 优先选择同集群的实例 在集群内随机
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

# 设置饥饿加载 使LoadBalancer在项目加载时就初始化 而不是第一次访问时加载 指定对user-service服务使用饥饿加载 可以有多个服务名称
ribbon:
  eager-load:
    clients: user-service
    enabled: true
